### PR TITLE
Added support for AWS profile

### PR DESCRIPTION
**Pull request by matijavizintin**
Added support for specifying the AWS profile that will be used to encrypt/decrypt the password.

The parameter is added as --profile=your_profile option and if not specified it defaults to 'default'.

### CODE REVIEW

**Comment by nsaje** [comment]
Parameters that are stored in the cyphertext were intended to hold the information that is necessary to be able to decrypt it - so I'm not sure `profile` belongs in here. It's local information and is of no use to a server machine decrypting that cyphertext. Even more, if you encrypt it with --profile=prod and that server doesn't have that profile, it won't be able to decrypt that secret. Is that intended?

**Comment by matijavizintin** [comment]
Profile is not encrypted. The format didn't change: kms:region=us-east-1:AQECAHjV44zy47+HwISLY89/H...

You have to specify the profile at encrypt and decrypt time.

**Comment by nsaje** [comment]
ah, ok then! Why not simply do `AWS_PROFILE=myprofile decrypt-secret ...` then? :-D

**Comment by nsaje** [comment]
tsk tsk, merged without :+1: :smile:

**Comment by matijavizintin** [comment]
@nsaje I remember using AWS_PROFILE env var didn't work in go.

**Pull request merged**
